config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }

  root to: 'spas#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/sign_up/complete'          => "users#sign_up_complete", as: :sign_up_complete
  get 'users/edit/complete'             => "users#edit_complete", as: :edit_complete
  get 'users/withdraw/:id/confirm'     => "users#withdraw_confirm", as: :withdraw_confirm
  get 'users/withdraw/complete'        => "users#withdraw_complete", as: :withdraw_complete
  resources :users, :only =>[:show,:edit,:update,:destroy]

  resources :favorites, :only =>[:create,:destroy]

  get 'spas/top'                        => "spas#top", as: :spa_top
  get 'spas/detail_search_form'         => "spas#detail_search_form", as: :detail_search_form
  get 'spas/detail_search'              => "spas#detail_search", as: :detail_search
  get 'spas/detail_search_list'         => "spas#detail_search_list", as: :detail_search_list
  get 'spas/index_search'               => "spas#index_search", as: :index_search
  get 'spas/index_search_list'          => "spas#index_search_list", as: :index_search_list
  get 'spas/spa_edit_top'               => "spas#spa_edit_top", as: :spa_edit_top
  resources :spas, :only =>[:show, :edit, :update]

  get 'reviews/complete'                => "reviews#complete", as: :review_complete
  get 'reviews/edit_complete'           => "reviews#edit_complete", as: :review_edit_complete
  resources :reviews, :only =>[:new,:create,:edit,:update,:destroy]

  get 'services/service_search_form'    => "services#service_search_form", as: :service_search_form
  get 'services/service_search'         => "services#service_search", as: :service_search
  get 'services/service_search_list'    => "services#service_search_list", as: :service_search_list

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_paranoid
  has_many :review
  belongs_to :area
  enum gender: {
    男性:1,女性:2,その他:3
  }

  enum age: {
    １０代:1,２０代:2,３０代:3,４０代:4,５０代:5,６０代:6,７０代以上:7
  }

  validates :nickname, presence: true, length: { maximum: 20 }
  validates :user_name, presence: true , length: { maximum: 20 }
  validates :kana_name, presence: true , length: { maximum: 30 }, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/}
  validates :gender, presence: true
  validates :age, presence: true
  validates :area_id, presence: true
  validates :password, presence: true , length: { minimum: 6 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    sign_up_complete_path
  end

  def after_sign_out_path_for(resource_name)
    withdraw_complete_path
  end

  def after_update_path_for(resource)
    edit_complete_path
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:edit_complete, :withdraw_confirm, :withdraw_complete, :sign_up_complete]


  def show
    if current_user.id == params[:id].to_i
      @reviews = Review.where(user_id: current_user.id).order(bathing_date: :desc).page(params[:page]).per(3)
    else
      redirect_to root_path and return
    end
  end

  def edit
  end

  def update
  end

  def edit_complete
  end

  def withdraw_confirm
  end

  def destroy
  end

  def withdraw_complete
  end

  def sign_up_complete
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit_complete.html.erb
<div class="col-xs-3">
</div>

<div class="col-xs-6">
	<div class="row">
		<div class="user_edit_complete_box">
    		<h2>ユーザ情報を更新しました</h2>
		</div>
	</div>
	<div class="row" style="text-align: center;">
		<%= link_to 'マイページへ', user_path(current_user), class: "back_btn"  %>
	</div>
</div>

<div class="col-xs-3">
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-1">
	</div>

	<div class="col-xs-10">
		<div class="mypage_wrapper">
			<div class="main-header">
	    		<h2>マイページ</h2>
	  		</div>
	  		<div class="my_page_box">
	  			<div class="user_info_box">
	  				<div class="sub-header">
	    				<h2>ユーザ情報</h2>
	  				</div>
	  				<table class="table user_info_table">
				      	<tbody>
				        	<tr>
					          	<th><p>ニックネーム</p></th>
					          	<td><p><%= current_user.nickname %></p></td>
					        </tr>
					        <tr>
					          	<th><p>氏名</p></th>
					          	<td><p><%= current_user.user_name %></p></td>
					        </tr>
					        <tr>
					          	<th><p>カナ氏名</p></th>
					          	<td><p><%= current_user.kana_name %></p></td>
					        </tr>
					        <tr>
					         	<th><p>性別</p></th>
					          	<td><p><%= current_user.gender %></p></td>
					        </tr>
					        <tr>
					         	<th><p>年代</p></th>
					          	<td><p><%= current_user.age %></p></td>
					        </tr>
					        <tr>
					         	<th><p>在住エリア</p></th>
					          	<td><p><%= "#{current_user.area.prefecture}(#{current_user.area.area_name})" %></p></td>
					        </tr>
					        <tr>
					          	<th><p>メールアドレス</p></th>
					          	<td><p><%= current_user.email %></p></td>
					        </tr>
					        <tr>
					          	<th><p>パスワード</p></th>
					          	<td><p>パスワードは表示できません</p></td>
					        </tr>
					    </tbody>
					</table>
					<div>
	  					<%= link_to "ユーザ編集", edit_user_registration_path(id: current_user.id), class: 'user_edit_btn' %>
	  				</div>
	  			</div>
	  			<div>
			    	<h2 class="sub-header">レビュー一覧</h2>
			    </div>
	  			<div class="col-xs-12 my_review_box">
			    			<div>
				    			<% @reviews.each do |review| %>
				    				<div class="col-xs-12 review_item_box">
				    					<div class="col-xs-12">
				    						<div class="col-xs-12" style="border-bottom: solid 3px  #535233;">
				    								<div class="col-xs-2">
						    							<h4>施設名</h4>
						    						</div>
						    						<div class="col-xs-6">
						    							<h4><%= review.spa.spa_name %></h4>
						    						</div>
													<div class="col-xs-2">
							    						<h4>入浴日</h4>
							    					</div>
							    					<div class="col-xs-2">
						    							<h4><%= review.bathing_date %></h4>
						    						</div>
				    						</div>
				    						<div class="col-xs-12" style="border-bottom: solid 3px  #535233; margin-bottom: 30px;">
				    							<div class="row">
				    								<div class="col-xs-2">
				    									<p>総合評価:</p>
				    								</div>
				    								<div class="col-xs-4">
				    									<%= render partial: 'spas/rating_star', locals: { rating:review.review_all_rating, star_size: 16} %>
				    									<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_all_rating.round(1)}点)" %></span>
				    								</div>
				    								<div class="col-xs-2">
				    									<p>お風呂の評価</p>
				    								</div>
				    								<div class="col-xs-4">
														<%= render partial: 'spas/rating_star', locals: { rating:review.review_bath_rating, star_size: 16} %>
														<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_all_rating.round(1)}点)" %></span>
				    								</div>
				    							</div>
				    							<div class="row">
				    								<div class="col-xs-2">
				    									<p>お食事の評価</p>
				    								</div>
				    								<div class="col-xs-4">
														<%= render partial: 'spas/rating_star', locals: { rating:review.review_meal_rating, star_size: 16} %>
														<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_all_rating.round(1)}点)" %></span>
				    								</div>
				    								<div class="col-xs-2">
				    									<p>その他の評価</p>
				    								</div>
				    								<div class="col-xs-4">
														<%= render partial: 'spas/rating_star', locals: { rating:review.review_other_rating, star_size: 16} %>
														<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_all_rating.round(1)}点)" %></span>
				    								</div>
				    							</div>
				    						</div>
				    						<div class="col-xs-12">
				    							<p>施設の感想</p>
				    						</div>
					    					<div class="review_impression_box col-xs-12" style="margin-bottom: 20px;" >
					    						<p><%= simple_format(review.spa_impression) %></p>
					    					</div>
				    						<div class="col-xs-3">
				    							<p>サービスの感想</p>
				    						</div>
				    						<div class="col-xs-9">
				    							<p>ベストサービス：<%= "#{review.service.service_name}(#{review.service.service_type})" %></p>
				    						</div>
					    					<div class="review_impression_box col-xs-12">
					    						<p><%= simple_format(review.service_impression) %></p>
					    					</div>
					    				</div>
					    				<div class="col-xs-12" style="margin-bottom: 20px;">
					    					<%= link_to "レビュー削除", review_path(id: review.id), class: 'review_delete_btn ', method: :delete, data: { confirm: '削除しますか？' } %>
					    				</div>
							        </div>
				    			<% end %>
				    		</div>
				    		<div class="col-xs-12"><%= paginate @reviews %></div>
	  		</div>
		</div>
	</div>

	<div class="col-xs-1">
	</div>

</div>

app/views/users/sign_up_complete.html.erb
<div class="col-xs-3">
</div>

<div class="col-xs-6">
	<div class="row">
		<div class="sign_up_complete_box">
    		<h2>登録が完了しました</h2>
		</div>
	</div>
	<div class="row" style="text-align: center;">
		<%= link_to 'トップへ', root_path, class: "back_btn"  %>
	</div>
</div>

<div class="col-xs-3">
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/withdraw_complete.html.erb
<div class="col-xs-3">
</div>

<div class="col-xs-6">
	<div class="row">
		<div class="withdraw_complete_box">
    		<h2>退会が完了しました</h2>
		</div>
	</div>
	<div class="row" style="text-align: center;">
		<%= link_to 'トップへ', root_path, class: "back_btn"  %>
	</div>
</div>

<div class="col-xs-3">
</div>

app/views/users/withdraw_confirm.html.erb
<div class="col-xs-3">
</div>

<div class="col-xs-6">
	<div class="row">
		<div class="withdraw_confirm_box">
    		<h2>本当に退会しますか？</h2>
    		<p>※退会後は取り消しできません</p>
		</div>
	</div>
	<div class="row" style="text-align: center;">
		<%= link_to "退会", user_registration_path, method: :delete, class: "confirm_btn" %>
		<%= link_to '戻る', user_path(current_user), class: "back_btn", style: "margin-left: 20px;"  %>
	</div>
</div>

<div class="col-xs-3">
</div>