config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }

  root to: 'spas#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/sign_up/complete'          => "users#sign_up_complete", as: :sign_up_complete
  get 'users/edit/complete'             => "users#edit_complete", as: :edit_complete
  get 'users/withdraw/:id/confirm'     => "users#withdraw_confirm", as: :withdraw_confirm
  get 'users/withdraw/complete'        => "users#withdraw_complete", as: :withdraw_complete
  resources :users, :only =>[:show,:edit,:update,:destroy]

  resources :favorites, :only =>[:create,:destroy]

  get 'spas/top'                        => "spas#top", as: :spa_top
  get 'spas/detail_search_form'         => "spas#detail_search_form", as: :detail_search_form
  get 'spas/detail_search'              => "spas#detail_search", as: :detail_search
  get 'spas/detail_search_list'         => "spas#detail_search_list", as: :detail_search_list
  get 'spas/index_search'               => "spas#index_search", as: :index_search
  get 'spas/index_search_list'          => "spas#index_search_list", as: :index_search_list
  get 'spas/spa_edit_top'               => "spas#spa_edit_top", as: :spa_edit_top
  resources :spas, :only =>[:show, :edit, :update]

  get 'reviews/complete'                => "reviews#complete", as: :review_complete
  get 'reviews/edit_complete'           => "reviews#edit_complete", as: :review_edit_complete
  resources :reviews, :only =>[:new,:create,:edit,:update,:destroy]

  get 'services/service_search_form'    => "services#service_search_form", as: :service_search_form
  get 'services/service_search'         => "services#service_search", as: :service_search
  get 'services/service_search_list'    => "services#service_search_list", as: :service_search_list

end

app/models/spa.rb
class Spa < ApplicationRecord
  belongs_to :area
  has_many :service
  has_many :review
  attachment :spa_image
end

app/controllers/spas_controller.rb
class SpasController < ApplicationController

  def top

  end

  def detail_search_form
  end

  def detail_search
  end

  def detail_search_list
  end

  def index_search
    area_id = params[:id]
    @search_area = Area.find_by(id: area_id)
    @search_spas = Spa.where(area_id: area_id).order(all_rating: :desc).page(params[:page]).per(3)
    @search_spas_size = Spa.where(area_id: area_id).count
  end

  def index_search_list
  end

  def show
    spa_id = params[:id]
    @selected_spa = Spa.find_by(id: spa_id)
    @spa_services = Service.where(spa_id: spa_id).order(vote: :desc)
    @reviews = Review.where(spa_id: spa_id).order(bathing_date: :desc).page(params[:page]).per(3)

  end

  def edit
    @spa = Spa.find_by(id: params[:id])
  end

  def update
    @spa = Spa.find(params[:id])
    @spa.update(spa_params)
    redirect_to root_path
  end

  def spa_edit_top

  end

  private

  def spa_params
    params.require(:spa).permit(:spa_image)
  end

end

app/views/spas/_area_search_btn.html.erb
<div class="col-xs-4" style="text-align: center;">
	<button type="button" class="top_search_btn" data-toggle="modal" data-target="<%= "#Modal#{prefecture_id}" %>" >
		<%= prefecture_name %>
	</button>
	<div class="modal fade" id="<%= "Modal#{prefecture_id}" %>"tabindex="-1" style="text-align: left;">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title"><%= prefecture_name %></h4>
				</div>
				<div class="modal-body">
					<% areas = Area.where(prefecture: prefecture_id) %>
						<% areas.each do |area| %>
							<p><%= link_to area.area_name, index_search_path(id: area.id), class: 'top_search_btn' %></p>
						<% end %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/spas/_rating_star.html.erb
<% if rating == 5 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 4.5 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-half.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 4.0 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 3.5 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-half.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 3.0 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 2.5 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-half.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 2.0 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 1.5 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-half.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 1.0 %>
	<img src="/assets/star-on.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% elsif rating >= 0.5 %>
	<img src="/assets/star-half.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% else %>
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
	<img src="/assets/star-off.png"  width="<%= star_size %>" height="<%= star_size %>" >
<% end %>

app/views/spas/edit.html.erb
<%= form_for(@spa) do |f| %>
  <!-- 追加部分 -->
  <h4>画像</h4>
  <%= f.attachment_field :spa_image %>
 
  <%= f.submit '投稿' %>
 
<% end %>

app/views/spas/index_search.html.erb
<div class="row">
	<div class="col-xs-1">
	</div>

	<div class="col-xs-10">
		<div class="top_search_list_wrapper">
	  		<div class="main-header">
	    		<h2>検索結果</h2>
	  		</div>

	  		<div class="top_search_list_box">
	  			<div class="sub-header">
	    			<h4><%= "#{@search_area.prefecture}(#{@search_area.area_name})にあるスーパー銭湯の検索結果 #{@search_spas_size}件" %></h4>
	  			</div>
	  					<% @search_spas.each do |spa| %>
						        <div class="col-xs-12 search_item_box">
							        <div class="col-xs-5" style="text-align: center;">
							        	<h4><%= spa.spa_name%></h4>
							        	<% if spa.spa_image.present? %>
											<%= attachment_image_tag spa, :spa_image, :fill, 300, 200, class: 'margin-bottom-10'%>
										<% else %>
											<img src="/assets/no-image.png" class="no-image" width="300" height="200" style="margin-bottom: 10px;">
										<% end %>
							        </div>
							        <div class="col-xs-7">
							        	<div class="row">
								        	<div class="col-xs-5">
								        		<h4>総合評価</h4>
								        	</div>
							        		<div class="col-xs-7">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  spa.all_rating, star_size: 32} %>
							        			<span style="font-size: 18px; vertical-align: middle;"><%= "(#{spa.all_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-5">
								        		<h4>お風呂の評価</h4>
								        	</div>
							        		<div class="col-xs-7">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  spa.bath_rating, star_size: 32} %>
							        			<span style="font-size: 18px; vertical-align: middle;"><%= "(#{spa.bath_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-5">
								        		<h4>お食事の評価</h4>
								        	</div>
							        		<div class="col-xs-7">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  spa.meal_rating, star_size: 32} %>
							        			<span style="font-size: 18px; vertical-align: middle;"><%= "(#{spa.meal_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-5">
								        		<h4>その他の評価</h4>
								        	</div>
							        		<div class="col-xs-7">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  spa.other_rating, star_size: 32} %>
							        			<span style="font-size: 18px; vertical-align: middle;"><%= "(#{spa.other_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-12">
								        		<h4><%= spa.address%></h4>
								        	</div>
							        	</div>
							        	<div class="row" style="text-align: center; margin-bottom: 20px;">
							        		<%= link_to "もっと見る", spa_path(id: spa.id), class: 'detail_btn' %>
							        	</div>
							        </div>
						        </div>
					    <% end %>
					    <div class="col-xs-12"><%= paginate @search_spas %></div>
			</div>
		</div>
	</div>
	<div class="col-xs-1">
	</div>
</div>

app/views/spas/show.html.erb
	

<div class="row">

	<div class="col-xs-1">
	</div>

	<div class="col-xs-10">
		<div class="spa_detail_wrapper">
	  		<div class="main-header">
	    		<h2><%= @selected_spa.spa_name %></h2>
	  		</div>

			<ul class="nav nav-tabs">
				<li class="active"><a href="#sampleContentA" data-toggle="tab">店舗評価</a></li>
				<li><a href="#sampleContentB" data-toggle="tab">サービスランキング</a></li>
				<li><a href="#sampleContentC" data-toggle="tab">基本情報</a></li>
			</ul>

			<div class="tab-content">
				<div class="tab-pane active" id="sampleContentA">
					<div class="col-xs-12 spa_detail_box">
						<div class="col-xs-12" style="border-bottom: 1px solid #951F2B;">
							        <div class="col-xs-5" style="text-align: center;">
							        	<h4><%= @selected_spa.spa_name%></h4>
							        	<% if @selected_spa.spa_image.present? %>
											<%= attachment_image_tag  @selected_spa, :spa_image, :fill, 300, 200, class: 'margin-bottom-10'%>
										<% else %>
											<img src="/assets/no-image.png" class="no-image" width="300" height="200" style="margin-bottom: 10px;">
										<% end %>
							        </div>
							        <div class="col-xs-7" style="margin-top: 40px;">
							        	<div class="row">
								        	<div class="col-xs-4">
								        		<h4>総合評価:</h4>
								        	</div>
							        		<div class="col-xs-8">
												<%= render partial: 'spas/rating_star', locals: { rating:  @selected_spa.all_rating, star_size: 35} %>
												<span style="font-size: 20px; vertical-align: middle;"><%= "(#{@selected_spa.all_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-4">
								        		<h4>お風呂の評価:</h4>
								        	</div>
							        		<div class="col-xs-8">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  @selected_spa.bath_rating, star_size: 35} %>
							        			<span style="font-size: 20px; vertical-align: middle;"><%= "(#{@selected_spa.bath_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-4">
								        		<h4>お食事の評価:</h4>
								        	</div>
							        		<div class="col-xs-8">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  @selected_spa.meal_rating, star_size: 35} %>
							        			<span style="font-size: 20px; vertical-align: middle;"><%= "(#{@selected_spa.meal_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								        <div class="row">
								        	<div class="col-xs-4">
								        		<h4>その他の評価:</h4>
								        	</div>
							        		<div class="col-xs-8">
							        			<%= render partial: 'spas/rating_star', locals: { rating:  @selected_spa.other_rating,star_size: 35} %>
							        			<span style="font-size: 20px; vertical-align: middle;"><%= "(#{@selected_spa.other_rating.round(1)}点)" %></span>
							        		</div>
								        </div>
								       	<div class="col-xs-12" style="text-align: center; margin: 10px 0px;">
							        		<%= link_to "レビューをする", new_review_path(id: @selected_spa.id), class: 'review_btn' %>
							        	</div>
							        </div>
						</div>
						<div class="col-xs-12">
							<div>
			    				<h4 class="sub-header">レビュー一覧</h4>
			    			</div>
			    			<div>
				    			<% @reviews.each do |review| %>
				    				<div class="col-xs-12 review_item_box">
				    					<div class="col-xs-12">
				    						<div class="col-xs-12" style="border-bottom: solid 3px  #535233;">
				    								<div class="col-xs-2">
						    							ユーザ名
						    						</div>
						    						<div class="col-xs-6">
						    							<%= review.user.nickname %> 様
						    						</div>
													<div class="col-xs-2">
							    						入浴日
							    					</div>
							    					<div class="col-xs-2">
						    							<%= review.bathing_date %>
						    						</div>
				    						</div>
				    						<div class="col-xs-12" style="border-bottom: solid 3px  #535233; margin-bottom: 30px;">
				    							<div class="row">
				    								<div class="col-xs-2">
				    									<p>総合評価:</p>
				    								</div>
				    								<div class="col-xs-4">
				    									<%= render partial: 'spas/rating_star', locals: { rating:review.review_all_rating, star_size: 16} %>
				    									<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_all_rating.round(1)}点)" %></span>
				    								</div>
				    								<div class="col-xs-2">
				    									<p>お風呂の評価</p>
				    								</div>
				    								<div class="col-xs-4">
														<%= render partial: 'spas/rating_star', locals: { rating:review.review_bath_rating, star_size: 16} %>
														<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_bath_rating.round(1)}点)" %></span>
				    								</div>
				    							</div>
				    							<div class="row">
				    								<div class="col-xs-2">
				    									<p>お食事の評価</p>
				    								</div>
				    								<div class="col-xs-4">
														<%= render partial: 'spas/rating_star', locals: { rating:review.review_meal_rating, star_size: 16} %>
														<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_meal_rating.round(1)}点)" %></span>
				    								</div>
				    								<div class="col-xs-2">
				    									<p>その他の評価</p>
				    								</div>
				    								<div class="col-xs-4">
														<%= render partial: 'spas/rating_star', locals: { rating:review.review_other_rating, star_size: 16} %>
														<span style="font-size: 12px; vertical-align: middle;"><%= "(#{review.review_other_rating.round(1)}点)" %></span>
				    								</div>
				    							</div>
				    						</div>
				    						<div class="col-xs-12">
				    							<p>施設の感想</p>
				    						</div>
					    					<div class="review_impression_box col-xs-12" style="margin-bottom: 20px;" >
					    						<p><%= simple_format(review.spa_impression) %></p>
					    					</div>
				    						<div class="col-xs-3">
				    							<p>サービスの感想</p>
				    						</div>
				    						<div class="col-xs-9">
				    							<p>ベストサービス：<%= "#{review.service.service_name}(#{review.service.service_type})" %></p>
				    						</div>
					    					<div class="review_impression_box col-xs-12">
					    						<p><%= simple_format(review.service_impression) %></p>
					    					</div>
					    				</div>
							        </div>
				    			<% end %>
				    		</div>
				    		<div class="col-xs-12"><%= paginate @reviews %></div>
			  			</div>
					 </div>

				</div>
				<div class="tab-pane" id="sampleContentB">
					<div class="col-xs-12 spa_detail_box">
						<div>
							<table class="table" style="margin-top: 20px;">
								<thead>
									<tr>
										<th>順位</th>
										<th>サービス名</th>
										<th>サービスの種類</th>
										<th>得票数</th>
									</tr>
								</thead>
								<tbody>
									<% @spa_services.each_with_index do |service, i| %>
										<tr>
											<th><%= "#{i+1}" %></th>
											<td><%= service.service_name %></td>
											<td><%= service.service_type %></td>
											<td><%= service.vote %></td>
										</tr>
									<% end %>
								</tbody>
							</table>
				 		</div>
			    	</div>
			    </div>
				<div class="tab-pane" id="sampleContentC">
					<div class="col-xs-12 spa_detail_box">
						<div>
							<table class="table" style="margin-top: 20px;">
								<tbody>
										<tr>
											<th>所在地</th>
											<td><%=  @selected_spa.address %></td>
										</tr>
										<tr>
											<th>電話番号</th>
											<td><%=  @selected_spa.phone_number %></td>
										</tr>
										<tr>
											<th>定休日</th>
											<td><%=  @selected_spa.regular_holiday %></td>
										</tr>
										<tr>
											<th>公式サイト</th>
											<td><%= @selected_spa.website %></td>
										</tr>
										<tr>
											<th>料金</th>
											<td><%= @selected_spa.charge %></td>
										</tr>
								</tbody>
							</table>
				 		</div>
			    	</div>
			    </div>
			</div>
	  	</div>
	</div>

	<div class="col-xs-1">
	</div>

</div>

app/views/spas/spa_edit_top.html.erb
スパ編集ページです。



<%= link_to "スパ編集", edit_spa_path(id: 1), class: 'detail_btn' %>